var EasyAutocomplete=function(c){return c.Configuration=function(b){function c(a,d){function b(d,g){for(var c in g)void 0===d[c]&&a.log("Property '"+c+"' does not exist in EasyAutocomplete options API."),"object"==typeof d[c]&&-1===jQuery.inArray(c,h)&&b(d[c],g[c])}b(f,d)}var f={data:"list-required",url:"list-required",dataType:"json",listLocation:function(a){return a},xmlElementName:"",getValue:function(a){return a},autocompleteOff:!0,placeholder:!1,ajaxCallback:function(){},matchResponseProperty:!1,
list:{sort:{enabled:!1,method:function(a,d){return a=f.getValue(a),d=f.getValue(d),d>a?-1:a>d?1:0}},maxNumberOfElements:6,hideOnEmptyPhrase:!0,match:{enabled:!1,caseSensitive:!1,method:function(a,d){return-1<a.search(d)}},showAnimation:{type:"normal",time:400,callback:function(){}},hideAnimation:{type:"normal",time:400,callback:function(){}},onClickEvent:function(){},onSelectItemEvent:function(){},onLoadEvent:function(){},onChooseEvent:function(){},onKeyEnterEvent:function(){},onMouseOverEvent:function(){},
onMouseOutEvent:function(){},onShowListEvent:function(){},onHideListEvent:function(){}},highlightPhrase:!0,theme:"",cssClasses:"",minCharNumber:0,requestDelay:0,adjustWidth:!0,ajaxSettings:{},preparePostData:function(a,d){return a},loggerEnabled:!0,template:"",categoriesAssigned:!1,categories:[{maxNumberOfElements:4}]},h=["ajaxSettings","template"];this.get=function(a){return f[a]};this.equals=function(a,d){return!(void 0===f[a]||null===f[a]||f[a]!==d)};this.checkDataUrlProperties=function(){return"list-required"!==
f.url||"list-required"!==f.data};this.checkRequiredProperties=function(){for(var a in f)if("required"===f[a])return logger.error("Option "+a+" must be defined"),!1;return!0};this.printPropertiesThatDoesntExist=function(a,d){c(a,d)};(function(){if("xml"===b.dataType&&(b.getValue||(b.getValue=function(a){return jQuery(a).text()}),b.list||(b.list={}),b.list.sort||(b.list.sort={}),b.list.sort.method=function(a,d){return a=b.getValue(a),d=b.getValue(d),d>a?-1:a>d?1:0},b.list.match||(b.list.match={}),b.list.match.method=
function(a,d){return-1<a.search(d)}),void 0!==b.categories&&b.categories instanceof Array){for(var a=[],d=0,g=b.categories.length;g>d;d+=1){var c=b.categories[d],h;for(h in f.categories[0])void 0===c[h]&&(c[h]=f.categories[0][h]);a.push(c)}b.categories=a}})();(function(){function a(d,b){var c=d||{},g;for(g in d)void 0!==b[g]&&null!==b[g]&&("object"!=typeof b[g]||b[g]instanceof Array?c[g]=b[g]:a(d[g],b[g]));return void 0!==b.data&&null!==b.data&&"object"==typeof b.data&&(c.data=b.data),c}f=a(f,b)})();
!0===f.loggerEnabled&&c(console,b);void 0!==b.ajaxSettings&&"object"==typeof b.ajaxSettings?f.ajaxSettings=b.ajaxSettings:f.ajaxSettings={};(function(){if("list-required"!==f.url&&"function"!=typeof f.url){var a=f.url;f.url=function(){return a}}void 0!==f.ajaxSettings.url&&"function"!=typeof f.ajaxSettings.url&&(a=f.ajaxSettings.url,f.ajaxSettings.url=function(){return a});if("string"==typeof f.listLocation){var d=f.listLocation;"XML"===f.dataType.toUpperCase()?f.listLocation=function(a){return jQuery(a).find(d)}:
f.listLocation=function(a){return a[d]}}if("string"==typeof f.getValue){var c=f.getValue;f.getValue=function(a){return a[c]}}void 0!==b.categories&&(f.categoriesAssigned=!0)})()},c}(EasyAutocomplete||{});EasyAutocomplete=function(c){return c.Logger=function(){this.error=function(b){console.log("ERROR: "+b)};this.warning=function(b){console.log("WARNING: "+b)}},c}(EasyAutocomplete||{});
EasyAutocomplete=function(c){return c.Constans=function(){var b={CONTAINER_CLASS:"easy-autocomplete-container",CONTAINER_ID:"eac-container-",WRAPPER_CSS_CLASS:"easy-autocomplete"};this.getValue=function(c){return b[c]}},c}(EasyAutocomplete||{});
EasyAutocomplete=function(c){return c.ListBuilderService=function(b,c){function f(a,d){function c(){var e,c={};return void 0!==a.xmlElementName&&(c.xmlElementName=a.xmlElementName),void 0!==a.listLocation?e=a.listLocation:void 0!==b.get("listLocation")&&(e=b.get("listLocation")),void 0!==e?"string"==typeof e?c.data=jQuery(d).find(e):"function"==typeof e&&(c.data=e(d)):c.data=d,c}function f(){var b={};return void 0!==a.listLocation?"string"==typeof a.listLocation?b.data=d[a.listLocation]:"function"==
typeof a.listLocation&&(b.data=a.listLocation(d)):b.data=d,b}var h={};if(h="XML"===b.get("dataType").toUpperCase()?c():f(),void 0!==a.header&&(h.header=a.header),void 0!==a.maxNumberOfElements&&(h.maxNumberOfElements=a.maxNumberOfElements),void 0!==b.get("list").maxNumberOfElements&&(h.maxListSize=b.get("list").maxNumberOfElements),void 0!==a.getValue)if("string"==typeof a.getValue){var k=a.getValue;h.getValue=function(a){return a[k]}}else"function"==typeof a.getValue&&(h.getValue=a.getValue);else h.getValue=
b.get("getValue");return h}function h(a){var d=[];return void 0===a.xmlElementName&&(a.xmlElementName=b.get("xmlElementName")),jQuery(a.data).find(a.xmlElementName).each(function(){d.push(this)}),d}this.init=function(a){var d=[],c={};return c.data=b.get("listLocation")(a),c.getValue=b.get("getValue"),c.maxListSize=b.get("list").maxNumberOfElements,d.push(c),d};this.updateCategories=function(a,d){if(b.get("categoriesAssigned")){a=[];for(var c=0;c<b.get("categories").length;c+=1){var h=f(b.get("categories")[c],
d);a.push(h)}}return a};this.convertXml=function(a){if("XML"===b.get("dataType").toUpperCase())for(var d=0;d<a.length;d+=1)a[d].data=h(a[d]);return a};this.processData=function(a,d){for(var g=0,h=a.length;h>g;g+=1)a[g].data=c(b,a[g],d);return a};this.checkIfDataExists=function(a){for(var b=0,c=a.length;c>b;b+=1)if(void 0!==a[b].data&&a[b].data instanceof Array&&0<a[b].data.length)return!0;return!1}},c}(EasyAutocomplete||{});
EasyAutocomplete=function(c){return c.proccess=function(b,k,f){function h(a,c){return b.get("list").match.caseSensitive||("string"==typeof a&&(a=a.toLowerCase()),c=c.toLowerCase()),!!b.get("list").match.method(a,c)}c.proccess.match=h;var a=k.data;return a=function(a,c){var d=[];if(b.get("list").match.enabled)for(var f=0,g=a.length;g>f;f+=1){var e=b.get("getValue")(a[f]);h(e,c)&&d.push(a[f])}else d=a;return d}(a,f),a=function(a){return void 0!==k.maxNumberOfElements&&a.length>k.maxNumberOfElements&&
(a=a.slice(0,k.maxNumberOfElements)),a}(a),a=function(a){return b.get("list").sort.enabled&&a.sort(b.get("list").sort.method),a}(a)},c}(EasyAutocomplete||{});
EasyAutocomplete=function(c){return c.Template=function(b){var c={basic:{type:"basic",method:function(b){return b},cssClass:""},description:{type:"description",fields:{description:"description"},method:function(b){return b+" - description"},cssClass:"eac-description"},iconLeft:{type:"iconLeft",fields:{icon:""},method:function(b){return b},cssClass:"eac-icon-left"},iconRight:{type:"iconRight",fields:{iconSrc:""},method:function(b){return b},cssClass:"eac-icon-right"},links:{type:"links",fields:{link:""},
method:function(b){return b},cssClass:""},custom:{type:"custom",method:function(){},cssClass:""}},f=function(b){var a,d=b.fields;return"description"===b.type?(a=c.description.method,"string"==typeof d.description?a=function(a,b){return a+" - <span>"+b[d.description]+"</span>"}:"function"==typeof d.description&&(a=function(a,b){return a+" - <span>"+d.description(b)+"</span>"}),a):"iconRight"===b.type?("string"==typeof d.iconSrc?a=function(a,b){return a+"<img class='eac-icon' src='"+b[d.iconSrc]+"' />"}:
"function"==typeof d.iconSrc&&(a=function(a,b){return a+"<img class='eac-icon' src='"+d.iconSrc(b)+"' />"}),a):"iconLeft"===b.type?("string"==typeof d.iconSrc?a=function(a,b){return"<img class='eac-icon' src='"+b[d.iconSrc]+"' />"+a}:"function"==typeof d.iconSrc&&(a=function(a,b){return"<img class='eac-icon' src='"+d.iconSrc(b)+"' />"+a}),a):"links"===b.type?("string"==typeof d.link?a=function(a,b){return"<a href='"+b[d.link]+"' >"+a+"</a>"}:"function"==typeof d.link&&(a=function(a,b){return"<a href='"+
d.link(b)+"' >"+a+"</a>"}),a):"custom"===b.type?b.method:c.basic.method};this.getTemplateClass=function(b){var a=function(){return""};return b&&b.type&&b.type&&c[b.type]?function(){var a=c[b.type].cssClass;return function(){return a}}():a}(b);this.build=b&&b.type&&b.type&&c[b.type]?f(b):c.basic.method},c}(EasyAutocomplete||{});
EasyAutocomplete=function(c){return c.main=function(b,k){function f(){function a(a,b){if(e.get("highlightPhrase")&&""!==b){var c=b.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&");c=(a+"").replace(new RegExp("("+c+")","gi"),"<b>$1</b>")}else c=a;return c}l.parent().hasClass(r.getValue("WRAPPER_CSS_CLASS"))&&(l.next("."+r.getValue("CONTAINER_CLASS")).remove(),l.unwrap());(function(){var a=jQuery("<div>"),b=r.getValue("WRAPPER_CSS_CLASS");e.get("theme")&&""!==e.get("theme")&&(b+=" eac-"+e.get("theme"));
e.get("cssClasses")&&""!==e.get("cssClasses")&&(b+=" "+e.get("cssClasses"));""!==z.getTemplateClass()&&(b+=" "+z.getTemplateClass());a.addClass(b);l.wrap(a);!0===e.get("adjustWidth")&&(a=l.outerWidth(),l.parent().css("width",a))})();(function(){var b=jQuery("<div>").addClass(r.getValue("CONTAINER_CLASS"));b.attr("id",h()).prepend(jQuery("<ul>"));(function(){b.on("show.eac",function(){switch(e.get("list").showAnimation.type){case "slide":var a=e.get("list").showAnimation.time,c=e.get("list").showAnimation.callback;
b.find("ul").slideDown(a,c);break;case "fade":a=e.get("list").showAnimation.time;c=e.get("list").showAnimation.callback;b.find("ul").fadeIn(a);c;break;default:b.find("ul").show()}e.get("list").onShowListEvent()}).on("hide.eac",function(){switch(e.get("list").hideAnimation.type){case "slide":var a=e.get("list").hideAnimation.time,c=e.get("list").hideAnimation.callback;b.find("ul").slideUp(a,c);break;case "fade":a=e.get("list").hideAnimation.time;c=e.get("list").hideAnimation.callback;b.find("ul").fadeOut(a,
c);break;default:b.find("ul").hide()}e.get("list").onHideListEvent()}).on("selectElement.eac",function(){b.find("ul li").removeClass("selected");b.find("ul li").eq(m).addClass("selected");e.get("list").onSelectItemEvent()}).on("loadElements.eac",function(c,d,f){var g="";c=b.find("ul");c.empty().detach();n=[];for(var h=0,q=0,k=d.length;k>q;q+=1){var v=d[q].data;if(0!==v.length){void 0!==d[q].header&&0<d[q].header.length&&c.append("<div class='eac-category' >"+d[q].header+"</div>");for(var x=0,p=v.length;p>
x&&h<d[q].maxListSize;x+=1)g=jQuery("<li><div class='eac-item'></div></li>"),function(){var b=x,c=h,k=d[q].getValue(v[b]);g.find(" > div").on("click",function(){l.val(k).trigger("change");m=c;u(c);e.get("list").onClickEvent();e.get("list").onChooseEvent()}).mouseover(function(){m=c;u(c);e.get("list").onMouseOverEvent()}).mouseout(function(){e.get("list").onMouseOutEvent()}).html(z.build(a(k,f),v[b]))}(),c.append(g),n.push(v[x]),h+=1}}b.append(c);e.get("list").onLoadEvent()})})();l.after(b)})();t=
jQuery("#"+h());e.get("placeholder")&&l.attr("placeholder",e.get("placeholder"))}function h(){var a=l.attr("id");return r.getValue("CONTAINER_ID")+a}function a(){A("autocompleteOff",!0)&&l.attr("autocomplete","off");(function(){l.focusout(function(){var a,b=l.val();e.get("list").match.caseSensitive||(b=b.toLowerCase());for(var c=0,d=n.length;d>c;c+=1)if(a=e.get("getValue")(n[c]),e.get("list").match.caseSensitive||(a=a.toLowerCase()),a===b)return m=c,void u(m)})})();(function(){l.off("keyup").keyup(function(a){function b(a){function b(){var a=
{},b=e.get("ajaxSettings")||{},c;for(c in b)a[c]=b[c];return a}if(!(a.length<e.get("minCharNumber"))){if("list-required"!==e.get("data")){var c=e.get("data"),f=p.init(c);f=p.updateCategories(f,c);f=p.processData(f,a);t.trigger("loadElements.eac",[f,a]);0<l.parent().find("li").length?d():g()}c=b();void 0!==c.url&&""!==c.url||(c.url=e.get("url"));void 0!==c.dataType&&""!==c.dataType||(c.dataType=e.get("dataType"));void 0!==c.url&&"list-required"!==c.url&&(c.url=c.url(a),c.data=e.get("preparePostData")(c.data,
a),jQuery.ajax(c).done(function(b){var c=p.init(b);c=p.updateCategories(c,b);c=p.convertXml(c);if(!1!==e.get("matchResponseProperty")?"string"==typeof e.get("matchResponseProperty")?b[e.get("matchResponseProperty")]===a:"function"==typeof e.get("matchResponseProperty")?e.get("matchResponseProperty")(b)===a:1:1)c=p.processData(c,a),t.trigger("loadElements.eac",[c,a]);p.checkIfDataExists(c)&&0<l.parent().find("li").length?d():g();e.get("ajaxCallback")()}).fail(function(){w.warning("Fail to load response data")}).always(function(){}))}}
switch(a.keyCode){case 27:g();l.trigger("blur");break;case 38:a.preventDefault();0<n.length&&0<m&&(--m,l.val(e.get("getValue")(n[m])),u(m));break;case 40:a.preventDefault();0<n.length&&m<n.length-1&&(m+=1,l.val(e.get("getValue")(n[m])),u(m));break;default:if(40<a.keyCode||8===a.keyCode){var c=l.val();!0!==e.get("list").hideOnEmptyPhrase||8!==a.keyCode||""!==c?0<e.get("requestDelay")?(void 0!==y&&clearTimeout(y),y=setTimeout(function(){b(c)},e.get("requestDelay"))):b(c):g()}}})})();(function(){l.on("keydown",
function(a){a=a||window.event;return 38===a.keyCode?(suppressKeypress=!0,!1):void 0}).keydown(function(a){13===a.keyCode&&-1<m&&(l.val(e.get("getValue")(n[m])),e.get("list").onKeyEnterEvent(),e.get("list").onChooseEvent(),m=-1,g(),a.preventDefault())})})();l.off("keypress");(function(){l.focus(function(){""!==l.val()&&0<n.length&&(m=-1,d())})})();(function(){l.blur(function(){setTimeout(function(){m=-1;g()},250)})})()}function d(){t.trigger("show.eac")}function g(){t.trigger("hide.eac")}function u(a){t.trigger("selectElement.eac",
a)}var y,r=new c.Constans,e=new c.Configuration(k),w=new c.Logger,z=new c.Template(k.template),p=new c.ListBuilderService(e,c.proccess),A=e.equals,l=b,t="",n=[],m=-1;c.consts=r;this.getConstants=function(){return r};this.getConfiguration=function(){return e};this.getContainer=function(){return t};this.getSelectedItemIndex=function(){return m};this.getItems=function(){return n};this.getItemData=function(a){return n.length<a||void 0===n[a]?-1:n[a]};this.getSelectedItemData=function(){return this.getItemData(m)};
this.build=function(){f()};this.init=function(){0===l.length?w.error("Input field doesn't exist."):e.checkDataUrlProperties()?e.checkRequiredProperties()?(f(),a()):w.error("Will not work without mentioned properties."):w.error("One of options variables 'data' or 'url' must be defined.")}},c.eacHandles=[],c.getHandle=function(b){return c.eacHandles[b]},c.inputHasId=function(b){return void 0!==jQuery(b).attr("id")&&0<jQuery(b).attr("id").length},c.assignRandomId=function(b){do var k="eac-"+Math.floor(1E4*
Math.random());while(0!==jQuery("#"+k).length);elementId=c.consts.getValue("CONTAINER_ID")+k;jQuery(b).attr("id",k)},c.setHandle=function(b,k){c.eacHandles[k]=b},c}(EasyAutocomplete||{});
!function(c){c.fn.easyAutocomplete=function(b){return this.each(function(){var k=c(this),f=new EasyAutocomplete.main(k,b);EasyAutocomplete.inputHasId(k)||EasyAutocomplete.assignRandomId(k);f.init();EasyAutocomplete.setHandle(f,k.attr("id"))})};c.fn.getSelectedItemIndex=function(){var b=c(this).attr("id");return void 0!==b?EasyAutocomplete.getHandle(b).getSelectedItemIndex():-1};c.fn.getItems=function(){var b=c(this).attr("id");return void 0!==b?EasyAutocomplete.getHandle(b).getItems():-1};c.fn.getItemData=
function(b){var k=c(this).attr("id");return void 0!==k&&-1<b?EasyAutocomplete.getHandle(k).getItemData(b):-1};c.fn.getSelectedItemData=function(){var b=c(this).attr("id");return void 0!==b?EasyAutocomplete.getHandle(b).getSelectedItemData():-1}}(jQuery);